//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturacion1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public int IdFactura { get; set; }
        public Nullable<int> FormaPago { get; set; }
        public Nullable<int> IdVendedores { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> idArticulo { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public decimal PrecioUnitario { get; set; }
    
        public virtual Articulos Articulos { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual CondicionPago CondicionPago { get; set; }
        public virtual vendedores vendedores { get; set; }
    }
}
