//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturacion1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public string Idusuario { get; set; }
        public string Nombre { get; set; }
        public string Contrasena { get; set; }
        public string Estado { get; set; }
        public string Rol { get; set; }
    }
}
